/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ZappPoc {
        /**
          * @default 'tap,zauth,tab,zout,mattermost,git,haldis,gamification,zess,events,pix,zinc'
         */
        "apps": string;
    }
    interface ZappV01 {
        /**
          * @default [     { img: "Gitea_Logo.svg", url: "https://git.zeus.gent" },     { img: "haldis_black.png", url: "https://haldis.zeus.gent" },     { img: "Mattermost_icon_denim.svg", url: "https://mattermost.zeus.gent"},     { img: "tap.ico", url: "https://tap.zeus.gent"},     { img: "tab.ico", url: "https://tab.zeus.gent" },     { img: "zess.svg", url: "https://zess.zeus.gent" },     { img: "zeus.svg", url: "https://zeus.gent" },     { img: "Gitea_Logo.svg", url: "https://git.zeus.gent" },     { img: "Mattermost_icon_denim.svg", url: "https://mattermost.zeus.gent" },     { img: "tap.ico", url: "https://tap.zeus.gent"},     { img: "zess.svg", url: "https://zess.zeus.gent" },     { img: "zeus.svg", url: "https://zeus.gent" },   ]
         */
        "apps": { img: string; url: string; }[];
    }
}
declare global {
    interface HTMLZappPocElement extends Components.ZappPoc, HTMLStencilElement {
    }
    var HTMLZappPocElement: {
        prototype: HTMLZappPocElement;
        new (): HTMLZappPocElement;
    };
    interface HTMLZappV01Element extends Components.ZappV01, HTMLStencilElement {
    }
    var HTMLZappV01Element: {
        prototype: HTMLZappV01Element;
        new (): HTMLZappV01Element;
    };
    interface HTMLElementTagNameMap {
        "zapp-poc": HTMLZappPocElement;
        "zapp-v01": HTMLZappV01Element;
    }
}
declare namespace LocalJSX {
    interface ZappPoc {
        /**
          * @default 'tap,zauth,tab,zout,mattermost,git,haldis,gamification,zess,events,pix,zinc'
         */
        "apps"?: string;
    }
    interface ZappV01 {
        /**
          * @default [     { img: "Gitea_Logo.svg", url: "https://git.zeus.gent" },     { img: "haldis_black.png", url: "https://haldis.zeus.gent" },     { img: "Mattermost_icon_denim.svg", url: "https://mattermost.zeus.gent"},     { img: "tap.ico", url: "https://tap.zeus.gent"},     { img: "tab.ico", url: "https://tab.zeus.gent" },     { img: "zess.svg", url: "https://zess.zeus.gent" },     { img: "zeus.svg", url: "https://zeus.gent" },     { img: "Gitea_Logo.svg", url: "https://git.zeus.gent" },     { img: "Mattermost_icon_denim.svg", url: "https://mattermost.zeus.gent" },     { img: "tap.ico", url: "https://tap.zeus.gent"},     { img: "zess.svg", url: "https://zess.zeus.gent" },     { img: "zeus.svg", url: "https://zeus.gent" },   ]
         */
        "apps"?: { img: string; url: string; }[];
    }
    interface IntrinsicElements {
        "zapp-poc": ZappPoc;
        "zapp-v01": ZappV01;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "zapp-poc": LocalJSX.ZappPoc & JSXBase.HTMLAttributes<HTMLZappPocElement>;
            "zapp-v01": LocalJSX.ZappV01 & JSXBase.HTMLAttributes<HTMLZappV01Element>;
        }
    }
}
